#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OrderDatabase")]
	public partial class OrderDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBurgerData(BurgerData instance);
    partial void UpdateBurgerData(BurgerData instance);
    partial void DeleteBurgerData(BurgerData instance);
    partial void InsertSubData(SubData instance);
    partial void UpdateSubData(SubData instance);
    partial void DeleteSubData(SubData instance);
    partial void InsertOrder(Order instance);
    partial void UpdateOrder(Order instance);
    partial void DeleteOrder(Order instance);
    #endregion
		
		public OrderDataDataContext() : 
				base(global::Final_Project.Properties.Settings.Default.OrderDatabaseConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public OrderDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrderDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrderDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrderDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BurgerData> BurgerDatas
		{
			get
			{
				return this.GetTable<BurgerData>();
			}
		}
		
		public System.Data.Linq.Table<SubData> SubDatas
		{
			get
			{
				return this.GetTable<SubData>();
			}
		}
		
		public System.Data.Linq.Table<Order> Orders
		{
			get
			{
				return this.GetTable<Order>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BurgerData")]
	public partial class BurgerData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SectionId;
		
		private int _OrderId;
		
		private string _Meat;
		
		private string _Bacon;
		
		private string _Cheese;
		
		private string _Lettuce;
		
		private string _Tomato;
		
		private string _Onion;
		
		private string _Ketchup;
		
		private string _Mustard;
		
		private string _Mayo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSectionIdChanging(int value);
    partial void OnSectionIdChanged();
    partial void OnOrderIdChanging(int value);
    partial void OnOrderIdChanged();
    partial void OnMeatChanging(string value);
    partial void OnMeatChanged();
    partial void OnBaconChanging(string value);
    partial void OnBaconChanged();
    partial void OnCheeseChanging(string value);
    partial void OnCheeseChanged();
    partial void OnLettuceChanging(string value);
    partial void OnLettuceChanged();
    partial void OnTomatoChanging(string value);
    partial void OnTomatoChanged();
    partial void OnOnionChanging(string value);
    partial void OnOnionChanged();
    partial void OnKetchupChanging(string value);
    partial void OnKetchupChanged();
    partial void OnMustardChanging(string value);
    partial void OnMustardChanged();
    partial void OnMayoChanging(string value);
    partial void OnMayoChanged();
    #endregion
		
		public BurgerData()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SectionId
		{
			get
			{
				return this._SectionId;
			}
			set
			{
				if ((this._SectionId != value))
				{
					this.OnSectionIdChanging(value);
					this.SendPropertyChanging();
					this._SectionId = value;
					this.SendPropertyChanged("SectionId");
					this.OnSectionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderId", DbType="Int NOT NULL")]
		public int OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				if ((this._OrderId != value))
				{
					this.OnOrderIdChanging(value);
					this.SendPropertyChanging();
					this._OrderId = value;
					this.SendPropertyChanged("OrderId");
					this.OnOrderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Meat", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Meat
		{
			get
			{
				return this._Meat;
			}
			set
			{
				if ((this._Meat != value))
				{
					this.OnMeatChanging(value);
					this.SendPropertyChanging();
					this._Meat = value;
					this.SendPropertyChanged("Meat");
					this.OnMeatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bacon", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string Bacon
		{
			get
			{
				return this._Bacon;
			}
			set
			{
				if ((this._Bacon != value))
				{
					this.OnBaconChanging(value);
					this.SendPropertyChanging();
					this._Bacon = value;
					this.SendPropertyChanged("Bacon");
					this.OnBaconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cheese", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Cheese
		{
			get
			{
				return this._Cheese;
			}
			set
			{
				if ((this._Cheese != value))
				{
					this.OnCheeseChanging(value);
					this.SendPropertyChanging();
					this._Cheese = value;
					this.SendPropertyChanged("Cheese");
					this.OnCheeseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lettuce", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Lettuce
		{
			get
			{
				return this._Lettuce;
			}
			set
			{
				if ((this._Lettuce != value))
				{
					this.OnLettuceChanging(value);
					this.SendPropertyChanging();
					this._Lettuce = value;
					this.SendPropertyChanged("Lettuce");
					this.OnLettuceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tomato", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tomato
		{
			get
			{
				return this._Tomato;
			}
			set
			{
				if ((this._Tomato != value))
				{
					this.OnTomatoChanging(value);
					this.SendPropertyChanging();
					this._Tomato = value;
					this.SendPropertyChanged("Tomato");
					this.OnTomatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Onion", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Onion
		{
			get
			{
				return this._Onion;
			}
			set
			{
				if ((this._Onion != value))
				{
					this.OnOnionChanging(value);
					this.SendPropertyChanging();
					this._Onion = value;
					this.SendPropertyChanged("Onion");
					this.OnOnionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ketchup", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ketchup
		{
			get
			{
				return this._Ketchup;
			}
			set
			{
				if ((this._Ketchup != value))
				{
					this.OnKetchupChanging(value);
					this.SendPropertyChanging();
					this._Ketchup = value;
					this.SendPropertyChanged("Ketchup");
					this.OnKetchupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mustard", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Mustard
		{
			get
			{
				return this._Mustard;
			}
			set
			{
				if ((this._Mustard != value))
				{
					this.OnMustardChanging(value);
					this.SendPropertyChanging();
					this._Mustard = value;
					this.SendPropertyChanged("Mustard");
					this.OnMustardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mayo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Mayo
		{
			get
			{
				return this._Mayo;
			}
			set
			{
				if ((this._Mayo != value))
				{
					this.OnMayoChanging(value);
					this.SendPropertyChanging();
					this._Mayo = value;
					this.SendPropertyChanged("Mayo");
					this.OnMayoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SubData")]
	public partial class SubData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SectionId;
		
		private int _OrderId;
		
		private string _Meat;
		
		private string _Cheese;
		
		private string _Lettuce;
		
		private string _Tomato;
		
		private string _Onion;
		
		private string _Pickle;
		
		private string _Mayo;
		
		private string _Mustard;
		
		private string _Vinaigrette;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSectionIdChanging(int value);
    partial void OnSectionIdChanged();
    partial void OnOrderIdChanging(int value);
    partial void OnOrderIdChanged();
    partial void OnMeatChanging(string value);
    partial void OnMeatChanged();
    partial void OnCheeseChanging(string value);
    partial void OnCheeseChanged();
    partial void OnLettuceChanging(string value);
    partial void OnLettuceChanged();
    partial void OnTomatoChanging(string value);
    partial void OnTomatoChanged();
    partial void OnOnionChanging(string value);
    partial void OnOnionChanged();
    partial void OnPickleChanging(string value);
    partial void OnPickleChanged();
    partial void OnMayoChanging(string value);
    partial void OnMayoChanged();
    partial void OnMustardChanging(string value);
    partial void OnMustardChanged();
    partial void OnVinaigretteChanging(string value);
    partial void OnVinaigretteChanged();
    #endregion
		
		public SubData()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SectionId
		{
			get
			{
				return this._SectionId;
			}
			set
			{
				if ((this._SectionId != value))
				{
					this.OnSectionIdChanging(value);
					this.SendPropertyChanging();
					this._SectionId = value;
					this.SendPropertyChanged("SectionId");
					this.OnSectionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderId", DbType="Int NOT NULL")]
		public int OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				if ((this._OrderId != value))
				{
					this.OnOrderIdChanging(value);
					this.SendPropertyChanging();
					this._OrderId = value;
					this.SendPropertyChanged("OrderId");
					this.OnOrderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Meat", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Meat
		{
			get
			{
				return this._Meat;
			}
			set
			{
				if ((this._Meat != value))
				{
					this.OnMeatChanging(value);
					this.SendPropertyChanging();
					this._Meat = value;
					this.SendPropertyChanged("Meat");
					this.OnMeatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cheese", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Cheese
		{
			get
			{
				return this._Cheese;
			}
			set
			{
				if ((this._Cheese != value))
				{
					this.OnCheeseChanging(value);
					this.SendPropertyChanging();
					this._Cheese = value;
					this.SendPropertyChanged("Cheese");
					this.OnCheeseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lettuce", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Lettuce
		{
			get
			{
				return this._Lettuce;
			}
			set
			{
				if ((this._Lettuce != value))
				{
					this.OnLettuceChanging(value);
					this.SendPropertyChanging();
					this._Lettuce = value;
					this.SendPropertyChanged("Lettuce");
					this.OnLettuceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tomato", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tomato
		{
			get
			{
				return this._Tomato;
			}
			set
			{
				if ((this._Tomato != value))
				{
					this.OnTomatoChanging(value);
					this.SendPropertyChanging();
					this._Tomato = value;
					this.SendPropertyChanged("Tomato");
					this.OnTomatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Onion", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Onion
		{
			get
			{
				return this._Onion;
			}
			set
			{
				if ((this._Onion != value))
				{
					this.OnOnionChanging(value);
					this.SendPropertyChanging();
					this._Onion = value;
					this.SendPropertyChanged("Onion");
					this.OnOnionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pickle", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Pickle
		{
			get
			{
				return this._Pickle;
			}
			set
			{
				if ((this._Pickle != value))
				{
					this.OnPickleChanging(value);
					this.SendPropertyChanging();
					this._Pickle = value;
					this.SendPropertyChanged("Pickle");
					this.OnPickleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mayo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Mayo
		{
			get
			{
				return this._Mayo;
			}
			set
			{
				if ((this._Mayo != value))
				{
					this.OnMayoChanging(value);
					this.SendPropertyChanging();
					this._Mayo = value;
					this.SendPropertyChanged("Mayo");
					this.OnMayoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mustard", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Mustard
		{
			get
			{
				return this._Mustard;
			}
			set
			{
				if ((this._Mustard != value))
				{
					this.OnMustardChanging(value);
					this.SendPropertyChanging();
					this._Mustard = value;
					this.SendPropertyChanged("Mustard");
					this.OnMustardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vinaigrette", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Vinaigrette
		{
			get
			{
				return this._Vinaigrette;
			}
			set
			{
				if ((this._Vinaigrette != value))
				{
					this.OnVinaigretteChanging(value);
					this.SendPropertyChanging();
					this._Vinaigrette = value;
					this.SendPropertyChanged("Vinaigrette");
					this.OnVinaigretteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Order]")]
	public partial class Order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OrderId;
		
		private string _Name;
		
		private string _HAMBURGER;
		
		private string _SUB;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrderIdChanging(int value);
    partial void OnOrderIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnHAMBURGERChanging(string value);
    partial void OnHAMBURGERChanged();
    partial void OnSUBChanging(string value);
    partial void OnSUBChanged();
    #endregion
		
		public Order()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				if ((this._OrderId != value))
				{
					this.OnOrderIdChanging(value);
					this.SendPropertyChanging();
					this._OrderId = value;
					this.SendPropertyChanged("OrderId");
					this.OnOrderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(10)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAMBURGER", DbType="NVarChar(50)")]
		public string HAMBURGER
		{
			get
			{
				return this._HAMBURGER;
			}
			set
			{
				if ((this._HAMBURGER != value))
				{
					this.OnHAMBURGERChanging(value);
					this.SendPropertyChanging();
					this._HAMBURGER = value;
					this.SendPropertyChanged("HAMBURGER");
					this.OnHAMBURGERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB", DbType="NVarChar(50)")]
		public string SUB
		{
			get
			{
				return this._SUB;
			}
			set
			{
				if ((this._SUB != value))
				{
					this.OnSUBChanging(value);
					this.SendPropertyChanging();
					this._SUB = value;
					this.SendPropertyChanged("SUB");
					this.OnSUBChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
